//1
function Add(x,y){
    console.log("Add",x+y);
}

Add(5,11);

//2
function Sub(x,y){
    console.log("Sub",x-y);
}

Sub(16,2);

//3
function mul(x,y){
    console.log("Mul",x*y);
}

mul(9,2);

//4
function div(x,y){
    console.log("div",x/y);
}

div(90,5);

//5
function sqr(x){
    console.log("sqr",x**2);
}

sqr(2);

//6
function cube(x){
    console.log("cube", x**3);
}

cube(3);

//7
function max(x,y){
    if(x>y){
    console.log("Max is",x);
    }else{
        console.log("Max is",y);
    }
}

max(2,4);

//8
function min(x,y){
    if(x<y){
    console.log("Min is",x);
    }else{
        console.log("min is",y);
    }
}

min(3,9);

//9
function even(x){
    if(x%2 == 0){
        console.log("Even");
    }
}

even(6);

//10
function odd(x){
    if(x%2 == 1){
        console.log("Odd");
    }
}

odd(9);

